import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import Inbox from "./components/inbox";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased`}>
        <Sidebar />
        {/* Apply a left margin equal to the collapsed sidebar width */}
        <main className="ml-16 transition-all duration-300">{children}</main>
        <Inbox />
      </body>
    </html>
  );
}
